[project]
name = "proyecto-capstone-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autopep8>=2.3.2",
    "bandit>=1.9.2",
    "boto3>=1.42.29",
    "datasets>=4.5.0",
    "fastapi[standard]>=0.128.0",
    "filterpy>=1.4.5",
    "flake8>=7.3.0",
    "hf-xet>=1.2.0",
    "httpx>=0.28.1",
    "isort>=7.0.0",
    "keras>=3.13.1",
    "mplsoccer>=1.6.1",
    "numpy>=2.4.1",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.3",
    "peft>=0.18.1",
    "pillow>=12.1.0",
    "protobuf>=6.33.4",
    "pydantic>=2.12.5",
    "python-decouple>=3.8",
    "scikit-learn>=1.8.0",
    "sqlalchemy>=2.0.45",
    "supervision>=0.27.0",
    "tenacity>=9.1.2",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
    "transformers>=4.57.5",
    "ultralytics>=8.4.3",
]
