from .routes import (
    BASE_RES_DIR as BASE_RES_DIR,
    OUTPUT_VIDEOS_DIR as OUTPUT_VIDEOS_DIR,
    OUTPUT_IMAGES_DIR as OUTPUT_IMAGES_DIR,
    INPUT_VIDEOS_DIR as INPUT_VIDEOS_DIR,
    MODELS_DIR as MODELS_DIR,
    OUTPUT_REPORTS_DIR as OUTPUT_REPORTS_DIR,
)
